# Generated by Django 4.2 on 2025-04-12 16:50

from django.db import migrations
from django.utils.text import slugify


def add_business_card_category(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model('wedding_app', 'Category')
    
    # Check if the business card category already exists
    if not Category.objects.filter(slug='business-card').exists():
        # Create a new business card category
        Category.objects.create(
            name='Business Card',
            slug='business-card',
            description='Professional business card designs for all industries. Choose from a variety of styles and customize them to suit your brand.',
            order=3  # Adjust this based on where you want it to appear in the list
        )


def remove_business_card_category(apps, schema_editor):
    # This is the reverse migration - if we need to roll back
    Category = apps.get_model('wedding_app', 'Category')
    Category.objects.filter(slug='business-card').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0003_order_userprofile_orderitem_cartitem'),
    ]

    operations = [
        migrations.RunPython(add_business_card_category, remove_business_card_category),
    ]
