# Generated by Django 4.2 on 2025-04-13 13:44

from django.db import migrations
from django.utils.text import slugify


def add_logo_category(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model('wedding_app', 'Category')
    
    # Check if the logo category already exists
    if not Category.objects.filter(slug='logo').exists():
        # Create a new logo category
        Category.objects.create(
            name='Logo',
            slug='logo',
            description='Professional logo designs for businesses, brands, and personal use. Choose from a variety of styles and customize them to reflect your brand identity.',
            order=4  # Adjust this based on where you want it to appear in the list
        )


def remove_logo_category(apps, schema_editor):
    # This is the reverse migration - if we need to roll back
    Category = apps.get_model('wedding_app', 'Category')
    Category.objects.filter(slug='logo').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0004_add_business_card_category'),
    ]

    operations = [
        migrations.RunPython(add_logo_category, remove_logo_category),
    ]
