# Generated by Django 4.2 on 2025-04-13 13:53

from django.db import migrations
from django.utils.text import slugify


def add_new_categories(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model('wedding_app', 'Category')
    
    # Add Social Media Design category
    if not Category.objects.filter(slug='social-media').exists():
        Category.objects.create(
            name='Social Media Design',
            slug='social-media',
            description='Professional social media designs including post templates, stories, profile covers, and profile pictures for all major platforms. Choose from a variety of styles and customize them to enhance your online presence.',
            order=5  # Adjust this based on where you want it to appear in the list
        )
    
    # Add Banner Design category
    if not Category.objects.filter(slug='banner').exists():
        Category.objects.create(
            name='Banner Design',
            slug='banner',
            description='Eye-catching banner designs for websites, social media, events, and advertising. Available in various sizes and formats to meet your specific needs. Perfect for digital marketing campaigns, website headers, and promotional materials.',
            order=6  # Adjust this based on where you want it to appear in the list
        )


def remove_new_categories(apps, schema_editor):
    # This is the reverse migration - if we need to roll back
    Category = apps.get_model('wedding_app', 'Category')
    Category.objects.filter(slug='social-media').delete()
    Category.objects.filter(slug='banner').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0005_add_logo_category'),
    ]

    operations = [
        migrations.RunPython(add_new_categories, remove_new_categories),
    ]
