# Generated by Django 4.2 on 2025-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0006_add_social_media_and_banner_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
